faiss_db:
  collection_name: "document_portal"

embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k:10

llm:
  grok:
    provider: "grok"
    model_name: "deepseek-r1-distill-llama-70b"
    temprature: 0
    max_output_tokens: 2048
  
  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temprature: 0
    max_output_tokens: 2048
